name: CI

on:
  push:
    branches: [ main, feature/typescript-conversion ]
  pull_request:
    branches: [ main, feature/typescript-conversion ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: vscode-extension/package-lock.json

    - name: Install dependencies
      run: |
        cd vscode-extension
        npm ci

    - name: Run ESLint
      run: |
        cd vscode-extension
        npm run lint

    - name: Build Extension
      run: |
        cd vscode-extension
        npm run compile

    - name: Run Tests
      run: |
        cd vscode-extension
        npm test

    - name: Package Extension
      run: |
        cd vscode-extension
        npm run vscode:prepublish

  coverage:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: vscode-extension/package-lock.json

    - name: Install dependencies
      run: |
        cd vscode-extension
        npm ci

    - name: Generate coverage report
      run: |
        cd vscode-extension
        npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./vscode-extension/coverage
        flags: typescript 